config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :works
  controller :works do
    get 'registration_new_work' => :registration_new
    post 'registration_create_work' => :registration_create
    get 'registration_edit_work' => :registration_edit
    post 'registration_update_work' => :registration_update
    get 'works/:id/users' => :show_work_users, as: 'work_users'
  end

  resources :accounts
  controller :accounts do
    get 'accounts/registration/new' => :registration_new, as: 'accounts_registration_new'
    post 'accounts/registration/create' => :registration_create, as: 'accounts_registration_create'
    get 'accounts/:id/registration/edit' => :registration_edit, as: 'accounts_registration_edit'
    patch 'accounts/:id/registration/update' => :registration_update
    put 'accounts/:id/registration/update' => :registration_update, as: 'accounts_registration_update'
  end
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'my_devise/registrations', confirmations: 'my_devise/confirmations', sessions: 'my_devise/sessions' }

  #controller :application do
  #  get 'authorize_user' => :authorize_user
  #end

  #controller :anonymous do
  #  get 'aaa' => :aaa
  #end

  controller :loged_user do
    get 'loged_user' => :wellcome
  end

  controller :loged_admin do
    get 'loged_admin' => :wellcome
  end

  #controller :sessions do
    #get 'login' => :new
    #post 'login' => :create
    #delete 'logout' => :destroy
  #end

  resources :users
  controller :users do
    get 'users/:id/pictures' => :pictures_show, as: 'show_users_pictures'
    patch 'users/:id/pictures' => :pictures_update, as: 'update_users_pictures'
    get 'users/:id/works' => :show_user_works, as: 'user_works'
    post 'users/create' => :create, as: 'users_create'
  end

  root 'shop#index'

  
  #controller :users do
  #  get 'show' => :show
  #end

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/loged_admin_controller.rb
class LogedAdminController < ApplicationController
  def wellcome
    if user_signed_in? && policy(current_user).is_admin
      respond_to do |format|
        format.html { render :wellcome }
        format.json { render json: { } }
      end
    else
      unauthorized
    end
  end
end

app/helpers/loged_admin_helper.rb
module LogedAdminHelper
end

app/views/loged_admin/_left_sidebar.html.erb
<div id="left_sidebar">

 	<table border="0" cellpadding="6" cellspacing="0">
     	<tr>
        <td id="left_sidebar_item" width="140"> <%= link_to 'My profile', edit_user_registration_path %> </td>
      </tr>
      <tr> 
       	<td id="left_sidebar_item" width="140">
       		<%= link_to 'List of users', users_path %> </td>
      </tr>                       
      <tr>
      	<td id="left_sidebar_item" width="140">
         <%= link_to 'List of works', works_path %> </td> 
      </tr>
      <tr>
      	<td id="left_sidebar_item" width="140"> <%= link_to 'Profile picture', show_users_pictures_path(current_user)%> </td>
      </tr>
      <tr>
          <td id="left_sidebar_item" width="140"> Admin 5 </td>
      </tr>
    </table>
</div>

app/views/loged_admin/wellcome.html.erb
<h1>LogedAdmin#wellcome</h1>
<p>Find me in app/views/loged_admin/wellcome.html.erb</p>

<h2> WELLCOME ADMIN !!! </h2>