config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :works
  controller :works do
    get 'registration_new_work' => :registration_new
    post 'registration_create_work' => :registration_create
    get 'registration_edit_work' => :registration_edit
    post 'registration_update_work' => :registration_update
    get 'works/:id/users' => :show_work_users, as: 'work_users'
  end

  resources :accounts
  controller :accounts do
    get 'accounts/registration/new' => :registration_new, as: 'accounts_registration_new'
    post 'accounts/registration/create' => :registration_create, as: 'accounts_registration_create'
    get 'accounts/:id/registration/edit' => :registration_edit, as: 'accounts_registration_edit'
    patch 'accounts/:id/registration/update' => :registration_update
    put 'accounts/:id/registration/update' => :registration_update, as: 'accounts_registration_update'
  end
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'my_devise/registrations', confirmations: 'my_devise/confirmations', sessions: 'my_devise/sessions' }

  #controller :application do
  #  get 'authorize_user' => :authorize_user
  #end

  #controller :anonymous do
  #  get 'aaa' => :aaa
  #end

  controller :loged_user do
    get 'loged_user' => :wellcome
  end

  controller :loged_admin do
    get 'loged_admin' => :wellcome
  end

  #controller :sessions do
    #get 'login' => :new
    #post 'login' => :create
    #delete 'logout' => :destroy
  #end

  resources :users
  controller :users do
    get 'users/:id/pictures' => :pictures_show, as: 'show_users_pictures'
    patch 'users/:id/pictures' => :pictures_update, as: 'update_users_pictures'
    get 'users/:id/works' => :show_user_works, as: 'user_works'
    post 'users/create' => :create, as: 'users_create'
  end

  root 'shop#index'

  
  #controller :users do
  #  get 'show' => :show
  #end

  mount Sidekiq::Web => '/sidekiq'

end

app/models/work.rb
class Work < ApplicationRecord
  has_many :users_works, dependent: :delete_all
  has_many :users, through: :users_works
  
  validates :title, presence: true, uniqueness: true

  generate_public_uid generator: PublicUid::Generators::NumberSecureRandom.new(1000000..9999999) #from public_uid gem

  def self.find_param(param)   #methos to find record according public_uid
    find_by! public_uid: param
  end
  
  def to_param    #override rails method to_params - it meanst public_uid attribute will be used in urls instead of id attribute
    "#{public_uid}"
  end

  #add record in table users_works, if this record doesn't exist
  def add_user(user)
    if self.users.include?(user)
      return false
    else
      self.users << user
      return true
    end
  end

  #return all users of work
  def work_users
    user_ids = Rails.cache.fetch("#{cache_key_with_version}/all_user_ids") { self.users.pluck(:id) }
    User.where(id: user_ids)   
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :update, :destroy, :show_work_users]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: { works: show_like_json(@works) } }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: { work: show_like_json(@work) } }
    end
  end

  # GET /works/new
  # creation of separate new work
  def new
    @work = Work.new
    respond_to do |format|
      format.html { render :new }
      format.json { render json: { work: show_like_json(@work) } }
    end
  end

  # GET /registration_new_work
  # creation of new work and to set a existing works durring user registration
  def registration_new
    if user_signed_in?
      @work = Work.new
      @works = Work.all
      respond_to do |format|
        format.html { render :registration_new }
        format.json { render json: { works: show_like_json(@works) } }
      end
    else
      unauthorized
    end
  end

  # GET /works/:id/edit
  # edition of separate work
  def edit
    if user_signed_in? && policy(Work.find_param(params[:id])).can_be_edited_by(current_user)
      set_work
    
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: { work: show_like_json(@work) } }
      end
    else
      unauthorized
    end
  end

  # GET /works/1/edit
  # edition of new work and to set a existing works in user profile
  def registration_edit
    if user_signed_in?
      @work = Work.new
      @works = Work.all
      @existed_works_id = current_user.work_ids

      respond_to do |format|
        format.html { render :registration_edit }
        format.json { render json: { all_works: show_like_json(@works), existed_work_ids: @existed_works_id } }
      end
    else
      unauthorized
    end
  end

  # POST /works
  # POST /works.json
  # creation of separate new work
  def create
    if user_signed_in? && policy(current_user).can_create_work
      @work = Work.new(work_params)

      respond_to do |format|
        if @work.save
          WorkJob.perform_later(current_user.email) #send email about new work has been created
          format.html { redirect_to root_path, notice: "Work was successfully created." }
          format.json { render status: 201, json: { work: show_like_json(@work), notice: "Work was successfully created."  } }
        else
          format.html { render :new; flash[:notice] = "Work was not created."  }
          format.json { render status: 422, json: { work: show_like_json(@work), notice: "Work was not created." } }
        end
      end
    else
      unauthorized
    end
  end

  # POST /registration_create_work
  # creation of new work and to set a existing works durring user registration
  def registration_create
    if user_signed_in? && policy(current_user).can_create_work
      current_user.update_existed_works(params[:existed_works_id])
  
      if !work_params[:title].empty?  #if there is a new work with params
        @work = Work.new(work_params)
        @work.add_user(current_user)  #calls model method
      end
      
      respond_to do |format|
        if ((defined? @work) && @work.save)
          WorkJob.perform_later(current_user.email) #send email about new work has been created
          format.html { redirect_to root_path, notice: "Works have been set and new work has been created." }
          format.json { render status: 201, json: { work: show_like_json(@work), notice: "Works have been set and new work has been created." } }
        else
          format.html { redirect_to root_path, notice: "Works have been set but new work has not been created." }
          format.json { render status: 201, json: { notice: "Works have been set but new work has not been created." } }
        end
      end  
    else
      unauthorized
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    if user_signed_in? && policy(@work).can_be_edited_by(current_user)
      respond_to do |format|
        if @work.update(work_params)         
          WorkJob.perform_later(current_user.email) #send email about new work has been created
          format.html { redirect_to @work, notice: "Work was successfully updated." }
          format.json { render status: 200, json: { work: show_like_json(@work), notice: "Work was successfully updated." } }
        else
          format.html { render :edit; flash[:notice] = "Work was not updated." }
          format.json { render status: 422, json: { work: show_like_json(@work), notice: "Work was not updated." } }
        end
      end
    else
      unauthorized
    end
  end

  # POST /registration_update_work
  # updating of new work and to set a existing works durring user registration
  def registration_update
    if user_signed_in? && policy(current_user).can_update_works
      current_user.update_existed_works(params[:existed_works_id])
      
      if !work_params[:title].empty?  #if there is a new work with params
        @work = Work.new(work_params)
        @work.add_user(current_user)  #calls model method
      end
      
      respond_to do |format|
        if ((defined? @work) && @work.save)
          WorkJob.perform_later(current_user.email) #send email about new work has been created
          format.html { redirect_to root_path, notice: "Works have been set and new work has been created." }
          format.json { render status: 201, json: { work: show_like_json(@work), notice: "Works have been set and new work has been created." } }
        else
          format.html { redirect_to root_path, notice: "Works have been set but new work has not been created." }
          format.json { render status: 201, json: { notice: "Works have been set but new work has not been created." } }
        end
      end
    else
      unauthorized
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    if user_signed_in? && policy(@work).can_be_destroyed_by(current_user)
      @work.destroy
      respond_to do |format|
        format.html { redirect_to works_path, notice: "Work has been destroyed." }
        format.json { render status: 204, json: { notice: "Work has been destroyed." } }
      end
    else
      unauthorized
    end
  end
  
  #GET /works/:id/works
  def show_work_users
    @work_users = @work.work_users

    respond_to do |format|
      format.html { render :show_work_users }
      format.json { render json: { users: UserSerializer.new(@work_users).as_json } }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_work
    @work = Work.find_param(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def work_params
    params.require(:work).permit(:title, :existed_works_id)
  end

  def show_like_json(works)
      WorkSerializer.new(works).as_json
  end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/edit.html.erb
<!-- View for a edditing separate works -->
<h1>Editing Works</h1>

<%= form_with(model: @work, local: true, url: work_path) do |form| %>
  <% if @work.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Please change the work title:<br />
    <%= form.text_field :title %>
  </div> <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/works/index.html.erb
<h1>Works</h1> <br>

<table class="elements_list">
  <tbody>
    <% @works.each do |work| %>
      <tr>
        <% if @is_admin %> <td><%= work.public_uid %> </td> <% end %>
                           <td><%= work.title %></td>
                           <td><%= link_to 'Show', work %></td>
        <% if @is_admin %> <td><%= link_to 'Edit', edit_work_path(work) %></td> <% end %>
        <% if @is_admin %> <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td> <% end %>
                           <td><%= link_to 'Show work users', work_users_path(work) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @is_admin %> <%= link_to 'New Work', new_work_path %> <% end %>

app/views/works/new.html.erb
<!-- View for a separate create of new work (e.g. by admin) --> 
<h2>Create a new Work</h2>

<br>

<%= form_with(model: @work, local: true, url: works_path) do |form| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
   <%= form.label :title %>
   <%= form.text_field :title %>
 </div>

 <br>

  <div class="actions">
    <%= form.submit "Create work"%>
  </div>
<% end %>

app/views/works/registration_edit.html.erb
<!-- View for a edditing user's works during registration or profile update-->
<h1>Editing registration Works</h1>

<%= form_with(model: @work, local: true, url: registration_update_work_path) do |form| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Please select from existing services:<br />
    <%= select_tag "existed_works_id", options_from_collection_for_select(@works, "id", "title"), multiple: true %>
  </div> <br />

  <div class="field">
    If you haven't found your service, please create new one:<br />
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/registration_new.html.erb
<%= form_with(model: @work, url: registration_create_work_path, local: true) do |form| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    Please select from existing services:<br />
    <%= select_tag "existed_works_id", options_from_collection_for_select(@works, "id", "title"), multiple: true %>
  </div> <br />

<% #if false %>
 <div class="field">
   If you haven't found your service, please create new one:<br />
   <%= form.text_field :title %>
 </div>
<% #end %>

  <div class="actions">
    <%= form.submit "Finish" %>
  </div>
<% end %>

app/views/works/show.html.erb
<u><strong> <%= @work.title%> </strong></u>
<br><br>


<strong>Workmen offering this work:</strong> <br>
<table class="elements_list">
    <% @work.users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
</table>

app/views/works/show_work_users.html.erb
<h3> Work "<%= @work.title %>" offer: </h3>
<br>

<table class="elements_list">
  <tr> 
    <td> <u> <strong> User name: </strong> </u> </td>
    <td> <u> <strong> Email: </strong> </u> </td>
    <td> <u> <strong> Address: </strong> </u> </td>
  <tr>

  <% @work_users.each do |user| %>
    <tr>
      <td> <%= user.username %> </td>
      <td> <%= user.email %> </td>
      <td> <%= user.address %> </td>
      <% if @is_admin %> <td> <%= link_to 'more info...', user_path(user) %> </td> <% end%>
    </tr>
  <% end %>
</table>