config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :works
  controller :works do
    get 'registration_new_work' => :registration_new
    post 'registration_create_work' => :registration_create
    get 'registration_edit_work' => :registration_edit
    post 'registration_update_work' => :registration_update
    get 'works/:id/users' => :show_work_users, as: 'work_users'
  end

  resources :accounts
  controller :accounts do
    get 'accounts/registration/new' => :registration_new, as: 'accounts_registration_new'
    post 'accounts/registration/create' => :registration_create, as: 'accounts_registration_create'
    get 'accounts/:id/registration/edit' => :registration_edit, as: 'accounts_registration_edit'
    patch 'accounts/:id/registration/update' => :registration_update
    put 'accounts/:id/registration/update' => :registration_update, as: 'accounts_registration_update'
  end
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'my_devise/registrations', confirmations: 'my_devise/confirmations', sessions: 'my_devise/sessions' }

  #controller :application do
  #  get 'authorize_user' => :authorize_user
  #end

  #controller :anonymous do
  #  get 'aaa' => :aaa
  #end

  controller :loged_user do
    get 'loged_user' => :wellcome
  end

  controller :loged_admin do
    get 'loged_admin' => :wellcome
  end

  #controller :sessions do
    #get 'login' => :new
    #post 'login' => :create
    #delete 'logout' => :destroy
  #end

  resources :users
  controller :users do
    get 'users/:id/pictures' => :pictures_show, as: 'show_users_pictures'
    patch 'users/:id/pictures' => :pictures_update, as: 'update_users_pictures'
    get 'users/:id/works' => :show_user_works, as: 'user_works'
    post 'users/create' => :create, as: 'users_create'
  end

  root 'shop#index'

  
  #controller :users do
  #  get 'show' => :show
  #end

  mount Sidekiq::Web => '/sidekiq'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
  
  has_one :account, dependent: :delete
  has_many :users_works, dependent: :delete_all
  has_many :works, through: :users_works

  has_one_attached :profile_picture, dependent: true  #connection with ActiveStorage - now is possible to use user.profile_picture
  
  validates :email, :username, presence: true
  validates :username, :email, uniqueness: true

  generate_public_uid generator: PublicUid::Generators::NumberSecureRandom.new(1000000..9999999) #from public_uid gem

  def self.find_param(param)   #methos to find record according public_uid
    find_by! public_uid: param
  end
  
  def to_param    #override rails method to_params - it meanst public_uid attribute will be used in urls instead of id attribute
    "#{public_uid}"
  end

  #update table users_works for current_user
  def update_existed_works(existed_works_id) 
    #self.work_ids = existed_works_id
    self.works = Work.where(id: existed_works_id)
    self.touch #update user's attribute "updated_at" (because cashing)
  end

  #return all works of user
  def user_works
    work_ids = Rails.cache.fetch("#{cache_key_with_version}/all_work_ids") { self.works.pluck(:id) } #here is used "cache_key_with_version" method, so the resulting cache_key will be something like "users/1/all_work_ids" but "cache_key_with_version" generates a string based on the model's `id` and `updated_at` attributes. This is a common convention and has the benefit of invalidating the cache whenever the product is updated.
    Work.where(id: work_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.jsonmodel: user
  def index
    if user_signed_in? && policy(current_user).is_admin
      @users = User.all
      respond_to do |format|
        format.html { render :index }
        format.json { render json: { users: show_like_json(@users) } }
      end
    else
      unauthorized
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if user_signed_in? && policy(current_user).can_see(User.find_param(params[:id]))
      set_user 
      respond_to do |format|
        format.html { render :show }
        format.json { render json: { user: show_like_json(@user) } }
      end
    else
      unauthorized
    end
  end

  # GET /users/new
  def new
    @user = User.new
    respond_to do |format|
      format.html { render :new }
      format.json { render json: { user: show_like_json(@user) } }
    end   
  end

  # GET /users/:id/edit
  def edit
    if user_signed_in? && policy(current_user).can_edit(User.find_param(params[:id]))
      set_user
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: { user: show_like_json(@user) } }
      end
    else
      unauthorized
    end
  end

  # POST /users
  # POST /users.json
  def create 
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render status: 201, json: { user: show_like_json(@user), notice: "User was successfully created." } }
      else
        format.html { render :new; flash[:notice] = "User was not created." }
        format.json { render status: 422, json: { user: show_like_json(@user), notice: "User was not created." } }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    binding.pry
    if user_signed_in? && policy(current_user).can_edit(User.find_param(params[:id]))
      set_user
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: "User was successfully updated." }
          format.json { render json: { user: show_like_json(@user), notice: "User was successfully updated." } }
        else
          format.html { render :edit; flash[:notice] = "User was not updated." }
          format.json { render status: 422, json: { user: show_like_json(@user), notice: "User was not updated." } }
        end
      end
    else
      unauthorized
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if user_signed_in? && policy(current_user).can_destroy(User.find_param(params[:id]))
      set_user
      @user.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: "User has been destroyed." }
        format.json { render status: 204, json: { notice: "User has been destroyed." } }
      end
    else
      unauthorized
    end
  end
  
  # GET /users/:id/pictures
  def pictures_show
    set_user
    respond_to do |format|
      format.html { render :pictures}
      format.json { render json: { user: show_like_json(@user) } }
    end
  end
  
  # PATCH /users/:id/pictures
  def pictures_update
    if user_signed_in? && policy(current_user).can_update_profile_picture(User.find_param(params[:id])) 
      set_user
      if params[:user] != nil && params[:user][:profile_picture] != nil
        @user.profile_picture.attach(params[:user][:profile_picture])
  
        respond_to do |format|
          format.html { render :pictures; flash[:notice] = "Profile picture has been changed." }
          format.json { render json: { user: show_like_json(@user), notice: "Profile picture has been changed." } }
        end
      else
        respond_to do |format|
          format.html { render :pictures; flash[:notice] = "Profile picture NOT changed!" }
          format.json { render status: 422, json: { user: show_like_json(@user), notice: "Profile picture NOT changed!" } }
        end
      end
    else
      unauthorized
    end
  end
  
  #GET /users/:id/works
  def show_user_works
    set_user
    @user_works = @user.user_works

    respond_to do |format|
      format.html { render :show_user_works }
      format.json { render json: { works: WorkSerializer.new(@user_works).as_json } }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :address, :email, :telephone, :password, :profile_picture, photos: [])
  end

  def set_user
    @user = User.find_param(params[:id])
  end

  def show_like_json(users)
      UserSerializer.new(users).as_json
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2> This is app/views/users/_from.html.erb </h2>

<% if false %>
  <%= form_with(model: user, local: true, multipart: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  
    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>
  
    <div class="field">
      <%= form.label :workmen %>
      <%= form.check_box :workmen %>
    </div>
  
    <div class="field">
      <%= form.label :customer %>
      <%= form.check_box :customer %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
  
    <div class="field">
      <%= form.label :telephone %>
      <%= form.text_field :telephone %>
    </div>
  
    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name %>
    </div>
  
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
  
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
  
    <div class="field">
      <%= form.label :profile_picture %>
      <%= form.file_field :profile_picture %>
    </div>
  
    <div class="field">
      <%= form.label :photos %>
      <%= form.file_field :photos, multiple: true %> <br>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit user's profile:</h2> <br>

<%= form_for(@user, as: :user, url: user_path(@user), html: { method: :put }) do |f| %>
  
  <div class="field">
    <%= f.label :username %> <br />
    <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
  </div>  <br />

  <div class="field">
    <%= f.label :email %> <br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>  <br />

  <div class="field">
    <%= f.label :address %> <br />
    <%= f.text_field :address, autocomplete: "address" %>
  </div>  <br />

  <div class="field">
    <%= f.label :telephone %> <br />
    <%= f.text_field :telephone, autocomplete: "telephone" %>
  </div>  <br />

  <div>
    Profile picture <br>
    <% if @user.profile_picture.attached? %>
      <%= image_tag @user.profile_picture %>
    <% else %>
      No profile picture.
    <% end %>
    <%= link_to 'Edit profile picture', update_users_pictures_path(@user) %>
  </div>  <br />


  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<br /><br />
<h3>Cancel this account</h3>

<%= button_to "Cancel this account", user_registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="elements_list">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td> 
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>Create new user:</h2>
<br />

<%= form_for(@user, url: users_create_path) do |f| %>
  
   <% if @user.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %> <br>
    <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
  </div> <br />

  <div class="field">
    <%= f.label :email %> <br>
    <%= f.text_field :email, autocomplete: "email" %>
  </div> <br />

  <div class="field">
    <%= f.label :address %> <br>
    <%= f.text_field :address, autocomplete: "address" %>
  </div> <br />

  <div class="field">
    <%= f.label :telephone %> <br>
    <%= f.text_field :telephone, autocomplete: "telephone" %>
  </div> <br />

  <div class="field">
    <%= f.label :password %> <br>
    <em>(4 characters minimum)</em> <br>
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div> <br />

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/users/pictures.html.erb
<h2>Profile picture - <%= @user.username %></h2>

<br>
<br>
<% if @user.profile_picture.attached? %>
  <%= image_tag @user.profile_picture %>
<% else %>
  No profile picture.
<% end %>
<br>
<br>

<div>
  Change?
  <%= form_with(model: @user, url: update_users_pictures_path(@user), local: true, multipart: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.file_field :profile_picture%>
    </div>
  
    <div class="actions">
      <%= form.submit "Update profile picture"%>
    </div>  
  <% end %>
</div>

app/views/users/show.html.erb
<h3> <%= @user.username %> </h3>

<table class="elements_list">
  <tr> <td>Public uid: </td> <td><%= @user.public_uid %></td> </tr>

  <tr> <td>Username: </td> <td><%= @user.username %></td> </tr>

  <tr> <td>Email: </td> <td><%= @user.email %></td> </tr>

  <tr> <td>Address: </td> <td><%= @user.address %></td> </tr>

  <tr> <td>Telephone: </td> <td><%= @user.telephone %></td> </tr>

  <tr>
    <td>Profile picture: </td>
    <td>
      <% if @user.profile_picture.attached? %>
        <%= image_tag @user.profile_picture %>
      <% else %>
        No profile picture.
      <% end %>  
    </td>
  </tr>

  <tr>
    <td>
      Account: <br>
      <% if @user.account %>
        <%= link_to "(edit account)", accounts_registration_edit_path(@user.account) %>
      <% else %>
        <%= link_to "(create account)", accounts_registration_new_path %>
      <% end %>
    </td>
    <td>
      <% if @user.account && @user.account.customer %>
           customer <br>
      <% end %>
      
      <% if @user.account && @user.account.workmen %>
           workmen <br>
      <% end %>

      <% if @user.account && @user.account.admin %>
           admin
      <% end %>
    </td>
  </tr>

  <tr>
    <td> Works: </td>
    <td>
      <% @user.user_works.each do |work| %>
        <%= work.title %> <br>
      <% end %>
    </td>
  </tr>

</table>

app/views/users/show_user_works.html.erb
<h2> Works of user: <%= @user.username %> </h2>

<% @user_works.each do |work| %>
  <%= work.title %> </br>
<% end %>