config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :works
  controller :works do
    get 'registration_new_work' => :registration_new
    post 'registration_create_work' => :registration_create
    get 'registration_edit_work' => :registration_edit
    post 'registration_update_work' => :registration_update
    get 'works/:id/users' => :show_work_users, as: 'work_users'
  end

  resources :accounts
  controller :accounts do
    get 'accounts/registration/new' => :registration_new, as: 'accounts_registration_new'
    post 'accounts/registration/create' => :registration_create, as: 'accounts_registration_create'
    get 'accounts/:id/registration/edit' => :registration_edit, as: 'accounts_registration_edit'
    patch 'accounts/:id/registration/update' => :registration_update
    put 'accounts/:id/registration/update' => :registration_update, as: 'accounts_registration_update'
  end
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'my_devise/registrations', confirmations: 'my_devise/confirmations', sessions: 'my_devise/sessions' }

  #controller :application do
  #  get 'authorize_user' => :authorize_user
  #end

  #controller :anonymous do
  #  get 'aaa' => :aaa
  #end

  controller :loged_user do
    get 'loged_user' => :wellcome
  end

  controller :loged_admin do
    get 'loged_admin' => :wellcome
  end

  #controller :sessions do
    #get 'login' => :new
    #post 'login' => :create
    #delete 'logout' => :destroy
  #end

  resources :users
  controller :users do
    get 'users/:id/pictures' => :pictures_show, as: 'show_users_pictures'
    patch 'users/:id/pictures' => :pictures_update, as: 'update_users_pictures'
    get 'users/:id/works' => :show_user_works, as: 'user_works'
    post 'users/create' => :create, as: 'users_create'
  end

  root 'shop#index'

  
  #controller :users do
  #  get 'show' => :show
  #end

  mount Sidekiq::Web => '/sidekiq'

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validate :atleast_one_is_checked

  generate_public_uid generator: PublicUid::Generators::NumberSecureRandom.new(1000000..9999999) #from public_uid gem

  def self.find_param(param)   #methos to find record according public_uid
    find_by! public_uid: param
  end
  
  def to_param    #override rails method to_params - it meanst public_uid attribute will be used in urls instead of id attribute
    "#{public_uid}"
  end

  def atleast_one_is_checked
      errors.add(:base, "Select atleast one output format type") unless workmen || customer || admin
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    #if user_signed_in? && policy(current_user).is_admin
      @accounts = Account.all
      respond_to do |format|
        format.html { render :index }
        format.json { render json: { accounts: show_like_json(@accounts) } }
      end
    #else
    #  unauthorized
    #end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    if user_signed_in? && policy(Account.find_param(params[:id])).can_be_seen_by(current_user)
      @account = set_account
      respond_to do |format|
        format.html { render :show }
        format.json { render json: { account: show_like_json(@account) } }
      end
    else
      unauthorized
    end
  end

  # GET /accounts/new
  def registration_new
    @account = Account.new
    respond_to do |format|
      format.html { render :new }
      format.json { render json: { account: show_like_json(@account) } }
    end
  end

  # GET /accounts/1/edit
  def registration_edit
    if user_signed_in? && policy(Account.find_param(params[:id])).can_be_seen_by(current_user)
      @account = set_account
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: { account: show_like_json(@account) } }
      end
    else
      unauthorized
    end
  end

  # POST /accounts
  # POST /accounts.json
  def registration_create
    if user_signed_in? 
      @current_account = current_user.account if current_user.account
      @account = Account.new(account_params)
      @account.user = current_user   
      
      respond_to do |format|
        if @account.save
          @current_account.delete if @current_account
          if (user_signed_in? && policy(current_user).can_create_work)
            format.html { redirect_to registration_new_work_path, notice: "Please continue with specifing your services." }
          else
            format.html { redirect_to root_path, notice: "Your account was succefully created." }
          end
          format.json { render status: 201, json: { account: show_like_json(@account), notice: "Your account was succefully created." } }
        else
          format.html { render :new; flash[:notice] = "Account was not created." }
          format.json { render status: 422, json: { account: show_like_json(@account), notice: "Account was not created." } }
        end
      end
    else
      unauthorized
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def registration_update
    if user_signed_in? && policy(Account.find_param(params[:id])).can_be_seen_by(current_user)
      @account = set_account    
      respond_to do |format|
        if (@account.update(account_params))
          current_user.reload
          if (user_signed_in? && policy(current_user).can_update_works)
            format.html { redirect_to registration_edit_work_path, notice: "Account was successfully updated." }
          else
            format.html { redirect_to root_path, notice: "Your account was succefully updated." }
          end
          format.json { render status: 200, json: { account: show_like_json(@account), notice: "Account was successfully updated." } }
        else
          format.html { render :edit; flash[:notice] = "Account was not updated." }
          format.json { render status: 422, json: { account: show_like_json(@account), notice: "Account was not updated." } }
        end
      end
    else
      unauthorized
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    if user_signed_in? && policy(Account.find_param(params[:id])).can_be_seen_by(current_user)
      @account = set_account
      @account.destroy
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Account was destroyed.' }
        format.json { render status: 204, json: {notice: "Account was destroyed." } }
      end
    else
      unauthorized
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find_param(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:workmen, :customer, :admin)
  end

  def show_like_json(accounts)
      AccountSerializer.new(accounts).as_json
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: @account, url: @route, local: true) do |f| %>
  
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    I am a workmen and I want to offer my working services: &nbsp
    <%= f.check_box :workmen%> <br />
  </div>

  <div class="field">
    I am a customer and I find some services: &nbsp
    <%= f.check_box :customer%> <br />
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit account:</h1>

<%= form_with(url: accounts_registration_update_path, local: true) do |f| %>
  <%= render 'form' %>
<% end %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>app/views/accounts/index.html.erb</h1>

<% if false %>
<h1>Accounts:</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', accounts_registration_edit_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', accounts_registration_new_path %>

<% end %>

app/views/accounts/new.html.erb
<h1>Please check who you are:</h1>
<br />

<%= form_with(url: accounts_registration_create_path, local: true) do |f| %>
  <%= render 'form' %>
<% end %>

app/views/accounts/show.html.erb
<h1>app/views/accounts/show.html.erb</h1>